export enum CHANNEL_TYPE {
    SMS = 'SMS',
    MESSENGER = 'MESSENGER',
    WATHS_APP = 'WATHS_APP',
    TELEGRAM = 'TELEGRAM'
}

export enum CONVERSION_STATUS {
    CLOSED = 'CLOSED',
    ACTIVATE = 'ACTIVATE',
    NEED_APPROVAL = 'NEED_APPROVAL',
}
