export enum CHANNEL_TYPE {
    SMS = 'SMS',
    MESSENGER = 'MESSENGER',
    WATHS_APP = 'WATHS_APP',
    TELEGRAM = 'TELEGRAM'
}

export enum CONVERSION_STATUS {
    CLOSE = 'CLOSE',
    ACTIVE = 'ACTIVE',
    NEED_APPROVAL = 'NEED_APPROVAL',
}
